# Generated by Django 4.0.6 on 2022-07-20 05:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_adressdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdressDetails',
            new_name='AddressDetails',
        ),
    ]
