# Generated by Django 4.0.6 on 2022-07-20 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_rename_adressdetails_addressdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to=settings.AUTH_USER_MODEL),
        ),
    ]
