# Generated by Django 4.0.3 on 2022-07-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderdetails_address'),
        ('cart', '0005_alter_addressdetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetails',
            name='order',
            field=models.ManyToManyField(related_name='Order', to='order.order'),
        ),
    ]
