# Generated by Django 4.0.3 on 2022-07-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderdetails_address'),
        ('cart', '0006_addressdetails_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressdetails',
            name='order',
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='orderdetails',
            field=models.ManyToManyField(related_name='orderdetails', to='order.orderdetails'),
        ),
    ]
