# Generated by Django 4.0.3 on 2022-07-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderdetails_address'),
        ('cart', '0007_remove_addressdetails_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetails',
            name='Phone_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='addressdetails',
            name='orderdetails',
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='orderdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderdetails', to='order.orderdetails'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='pin_code',
            field=models.PositiveIntegerField(),
        ),
    ]
