# Generated by Django 4.0.6 on 2022-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_addressdetails_user'),
        ('order', '0002_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='address',
            field=models.ManyToManyField(related_name='address', to='cart.addressdetails'),
        ),
    ]
