# Generated by Django 4.0.3 on 2022-07-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderdetails_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='address',
        ),
    ]
